// import "../(root)/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ForgotPasswordLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
